create judge-answer service
suzukikeita1/intern-suzuki_drive-meister pull request #51
Opened 2024-07-11 04:38 UTC by suzukikeita1

## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

- #30 
- #31 

## ⛏ 変更内容 / Details of Changes

- 正誤判定の結果を保存するjudge-answer serviceを作成
- 用意した問題を一巡するまで同じ問題が出題されないようにするsort-next-cards serviceを作成

## 📸 スクリーンショット / Screenshots

## レビューするポイント (Points for review):

 - 問題を解き終わった後、finishボタンを押すと正しい結果が表示されるか？
 - 用意した問題を一巡するまで同じ問題が出題されないか？

2024-07-11 04:55 UTC, suzukikeita1 commented
開発者ツールで「finish」ボタン、「もどる」ボタンをクリックしても画面遷移しないかもしれません。
開発者ツールを閉じてクリックすると遷移できると思います。
後で修正しておきます。

2024-07-11 06:10 UTC, k-hayashi-dott commented
tap と click のイベント差かな。
tap だと swipe するためにイベントをキャンセルしているからかもね。

2024-07-11 06:33 UTC, k-hayashi-dott commented on drive-meister/src/app/quiz/quiz.component.ts
> +      this.sortNextCardsService.displayedCardsIndices
今後、DB移行されることを考えるとあんまり使われないロジックになりそうな？
一度使ったIndexは使わない、とするよりは
対象の配列数から、ランダムに数字を並び替えてその順番に配列から取得するとしたほうがよいかなと。

2024-07-11 07:14 UTC, k-hayashi-dott requested changes

2024-07-11 07:14 UTC, k-hayashi-dott commented on drive-meister/src/app/judge/judge.component.ts
> +        console.log(this.direction);
deubg log はけしておきましょう。（ここだけじゃなく）

2024-07-11 09:40 UTC, k-hayashi-dott commented on drive-meister/src/app/quiz/quiz.component.ts
> +      this.sortNextCardsService.displayedCardsIndices
cards に id を付与する
count 内で乱数でランダムな順序を作成する
id で 1件ずつ取得する
そのid の問題がなければ次の問題を取得する

2024-07-21 04:32 UTC, suzukikeita1 commented on drive-meister/src/app/quiz-index.Service.ts
> +export class QuizIndexService {
サービス名及びクラス名が適切ではないと思ったので変えました

2024-07-21 04:34 UTC, suzukikeita1 commented on drive-meister/src/app/quiz-state.service.ts
> +}
コンポーネント間でクイズのデータを共有するためのサービスを作成しました

2024-07-21 04:36 UTC, suzukikeita1 commented on drive-meister/src/app/quiz-state.service.ts
コンポーネント間でクイズのデータを共有するためのサービスを作成しました

2024-07-22 02:29 UTC, k-hayashi-dott approved these changes

2024-07-22 03:57 UTC, merged